---
controller:
  hostNetwork: true

  service:
    enabled: true
    type: LoadBalancer
    annotations:
      metallb.io/address-pool: ingress-address-pool
      metallb.io/allow-shared-ip: ingress-address-pool

  # TODO: enable metrics
  metrics:
    enabled: false
    serviceMonitor:
      enabled: false
