---
apiVersion: builtin
kind: HelmChartInflationGenerator
metadata:
  name: synology-csi
name: synology-csi
repo: https://zebernst.github.io/synology-csi-talos
version: 0.9.4
releaseName: synology-csi
valuesFile: values.yaml
additionalValuesFiles:
  - values.enc.yaml
