---
# Schema for infrastructure configuration
# This schema validates only the essential required fields.
# See the generated site.yaml from 'klabctl init' for complete examples and defaults.
componentName: infra
version: v1
description: Infrastructure provisioning configuration for Kubernetes clusters

values:
  provider.name:
    type: string
    required: true
    description: Infrastructure provider name
    example: "proxmox"
  
  cluster.name:
    type: string
    required: true
    description: Kubernetes cluster name
    example: "my-cluster"
  
  cluster.endpoint:
    type: string
    required: true
    description: Kubernetes API endpoint URL
    example: "https://192.168.1.10:6443"
  
  cluster.virtualSharedIp:
    type: string
    required: true
    format: ipv4
    description: Virtual IP shared across control plane nodes
    example: "192.168.1.100"
  
  cluster.defaultGateway:
    type: string
    required: true
    format: ipv4
    description: Default gateway for the cluster network
    example: "192.168.1.1"

