---
# dnsmasq:
#   customDnsEntries:
#     - address=/nas/192.168.178.10

#   customCnameEntries:
#     - cname=foo.nas,nas

persistentVolumeClaim:
  enabled: true

serviceWeb:
  type: ClusterIP

serviceDns:
  loadBalancerIP: 0.0.0.0
  annotations:
    metallb.io/address-pool: pihole-address-pool
    metallb.io/allow-shared-ip: pihole-address-pool
  type: LoadBalancer

doh:
  enabled: true
  pullPolicy: Always
  envVars: {
    DOH_UPSTREAM: "https://1.1.1.1/dns-query"
  }

ingress:
  enabled: true
  hosts:
    - pihole.kubernetes.lan.basmaas.nl
  annotations:
    kubernetes.io/ingress.class: nginx

DNS1: "1.1.1.1"
DNS2: "1.0.0.1"
