apiVersion: klab/v1alpha1
kind: Site
metadata:
  name: myhome
spec:

  # Apps “base” (remote) + site overlays (local)
  apps:
    base:
      source: "https://github.com/bamaas/HomeLab-2.0"
      ref: "v1.2.3"      # pin to a tag or commit SHA (avoid main)
      path: "apps/base"

    # Per-component overlays; each becomes its own Argo CD Application (for visibility)
    catalog:

      pihole:
        enabled: true
        values:
          host: pihole.dev.kubernetes.lan.basmaas.nl
          ip: 192.168.8.120
          password: asdfasd

      cilium:
        enabled: true

      ingress-nginx:
        enabled: true
        values:
          ip: 192.168.8.100

      external-dns:
        enabled: true

      metallb:
        enabled: true

      cert-manager:
        enabled: true
        values:
          letsencrypt:
            email: test@test.com
          cloudflare:
            apiToken: 1234567890