---
apiVersion: builtin
kind: HelmChartInflationGenerator
metadata:
  name: argo-cd
name: argo-cd
repo: https://argoproj.github.io/argo-helm
version: 7.8.23
releaseName: argo-cd
valuesFile: values.yaml
