apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: system
  namespace: argocd
spec:
  description: System infrastructure - can create some cluster resources
  
  sourceRepos:
    - '*'
  
  destinations:
    - namespace: '*'
      server: https://kubernetes.default.svc
  
  # System apps can create SOME cluster resources (but not Namespaces)
  clusterResourceWhitelist:
    - group: 'rbac.authorization.k8s.io'
      kind: ClusterRole
    - group: 'rbac.authorization.k8s.io'
      kind: ClusterRoleBinding
    - group: 'apiextensions.k8s.io'
      kind: CustomResourceDefinition
    - group: 'admissionregistration.k8s.io'
      kind: ValidatingWebhookConfiguration
    - group: 'admissionregistration.k8s.io'
      kind: MutatingWebhookConfiguration
    # Note: NO Namespace in this list!
  
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'