---
apiVersion: builtin
kind: HelmChartInflationGenerator
metadata:
  name: victoria-logs-single
name: victoria-logs-single
repo: https://victoriametrics.github.io/helm-charts/
version: 0.11.3
releaseName: victoria-logs-single
valuesFile: values.yaml
