---
victoria-metrics-operator:
  enabled: false

grafana:
  enabled: true
  datasources:
    datasources.yaml:
      apiVersion: 1
      datasources:
        - name: VictoriaLogs
          type: victoriametrics-logs-datasource
          access: proxy
          url: http://victoria-logs-single-server:9428
          isDefault: false
          jsonData:
            maxLines: 1000
            httpMethod: GET
  persistence:
    enabled: true
    size: 10Gi
    storageClassName: ""
  securityContext:
    runAsUser: 472
    runAsGroup: 472
    fsGroup: 472
  initChownData:
    enabled: false
  sidecar:
    datasources:
      enabled: true
      initDatasources: true
      label: grafana_datasource
    dashboards:
      enabled: true
      # Enable custom dashboards
      searchNamespace: ALL
      folderAnnotation: grafana_dashboard_folder
      provider:
        name: default
        orgid: 1
        foldersFromFilesStructure: true
      folder: /var/lib/grafana/dashboards
      defaultFolderName: default
      multicluster: false
  forceDeployDatasource: false
  extraInitContainers:
    - name: "load-vm-ds-plugin"
      image: "curlimages/curl:7.85.0"
      command: ["/bin/sh"]
      workingDir: "/var/lib/grafana"
      securityContext:
        runAsUser: 472
        runAsNonRoot: true
        runAsGroup: 472
      args:
        - "-c"
        - |
          set -ex
          mkdir -p /var/lib/grafana/plugins/
          ver=$(curl -s -L https://api.github.com/repos/VictoriaMetrics/victorialogs-datasource/releases/latest | grep -oE 'v[0-9]+\.[0-9]+\.[0-9]+' | head -1)
          curl -L https://github.com/VictoriaMetrics/victorialogs-datasource/releases/download/$ver/victoriametrics-logs-datasource-$ver.tar.gz -o /var/lib/grafana/plugins/vl-plugin.tar.gz
          tar -xf /var/lib/grafana/plugins/vl-plugin.tar.gz -C /var/lib/grafana/plugins/
          rm /var/lib/grafana/plugins/vl-plugin.tar.gz
      volumeMounts:
        - name: storage
          mountPath: /var/lib/grafana
  ingress:
    enabled: true
    ingressClassName: nginx
