apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: platform
  namespace: argocd
spec:
  description: Platform team - can manage namespaces and cluster resources
  
  sourceRepos:
    - '*'
  
  destinations:
    - namespace: '*'
      server: https://kubernetes.default.svc
  
  # Platform can create/manage cluster-scoped resources
  clusterResourceWhitelist:
    - group: ''
      kind: Namespace
    - group: 'rbac.authorization.k8s.io'
      kind: ClusterRole
    - group: 'rbac.authorization.k8s.io'
      kind: ClusterRoleBinding
    - group: 'storage.k8s.io'
      kind: StorageClass
    - group: 'scheduling.k8s.io'
      kind: PriorityClass
    - group: '*'
      kind: '*'
  
  # Platform can manage any namespace-scoped resources
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'