---
componentName: ingress-nginx
schemaVersion: v1

values:
  ip:
    type: string
    required: true
    format: ipv4
    description: "LoadBalancer IP for ingress-nginx service"
    example: "192.168.1.150"
